Aktualizace
LeanMapper/LeanMapper.github.io pull request #10
Opened 2017-01-04 21:07 UTC by janpecha

* zapnuto zvýrazňování syntaxe
* aktualizován changelog
* přidána stránka Mapper
* přidána stránka Ukázky použití a zajímavá řešení + CamelCase to under_score mapper (přesunuto z wiki https://github.com/Tharos/LeanMapper/wiki/camelcase-to-under-score-mapper)
* přidána stránka EntityFactory
* přidána stránka Integrace Lean Mapper do aplikace (přesunuto z wiki https://github.com/Tharos/LeanMapper/wiki/integrace-lean-mapperu-do-aplikace)

2017-01-08 09:41 UTC, castamir requested changes
prosim o vyjadreni pripadne o upravy

2017-01-08 09:41 UTC, castamir commented on cs/docs/integrace-do-aplikace.md
> +    - LeanMapper\DefaultEntityFactory
pokud si dobre vzpominam, tak tohle neni potreba definovat, existuje DI\Extension pro nette a dokonce regne i repozitare viz https://github.com/Tharos/LeanMapper/blob/develop/src/LeanMapper/Bridges/Nette/DI/LeanMapperExtension.php

2017-01-08 09:41 UTC, castamir commented on cs/docs/integrace-do-aplikace.md
> +**Tip:** pokud nechcete, nebo nemůžete použít anotaci `@inject`, lze pro předání repositáře použít constructor nebo [`inject*()` metodu](http://pla.nette.org/cs/inject-autowire).
Tohle bych napsal naopak. Konstruktor je jedine spravne reseni predani zavislosti. Injectovani, at uz pres anotace nebo pres metodu, je jen vseobecne pouzivana berlicka specialne pro presentery, aby se vyvojari vyhnuli problemu "contructor hell" pri velke dedicnosti, ktera je u presenteru bezna. V modelu aplikace (ve smyslu MVC) je nutne predat zavislosti vyhradne pres konstruktor.

2017-01-08 09:41 UTC, castamir commented on cs/tutorials/camelcase-to-underscore-mapper.md
> +K zprovoznění této funkcionality postačí upravit [**mapper**](/cs/docs/mapper/), tedy třídu, která dědí po `LeanMapper\DefaultMapper` nebo jen implementuje rozhraní `LeanMapper\IMapper`. Nejprve si p
Striktne vzato, metody pro prevod nazvu z jedne konvence do jine nepatri do Mapperu, ale jinam, kvuli pouzitelnosti mimo LeanMapper. Jejich implementace muze zustat staticka (stejne jako trida Strings z Nette) a v Mapperu to jen pouzit.

2017-01-08 09:42 UTC, castamir commented
Jinak vyborna prace! ;-)

2017-01-08 17:52 UTC, janpecha commented on cs/docs/integrace-do-aplikace.md
> +    - LeanMapper\DefaultEntityFactory
Rozšíření pro Nette nepoužívám, ale ano, i to je jedna z cest. Ideální by asi bylo zmínit oboje - DI rozšíření jako doporučenou cestu a tohle nastavení jako alternativu pro ty, kteří nechtějí nemůžou DI rozšíření použít.

2017-01-08 17:52 UTC, janpecha commented on cs/tutorials/camelcase-to-underscore-mapper.md
> +K zprovoznění této funkcionality postačí upravit [**mapper**](/cs/docs/mapper/), tedy třídu, která dědí po `LeanMapper\DefaultMapper` nebo jen implementuje rozhraní `LeanMapper\IMapper`. Nejprve si p
Striktně vzato asi ano, ale pokud nikde jinde ty metody nepotřebujeme, nedává jejich vyčlenění do další třídy smysl. Navíc tohle je jen příklad, je asi zbytečné to komplikovat dalšími třídami.

2017-01-08 17:53 UTC, janpecha commented on cs/docs/integrace-do-aplikace.md
> +**Tip:** pokud nechcete, nebo nemůžete použít anotaci `@inject`, lze pro předání repositáře použít constructor nebo [`inject*()` metodu](http://pla.nette.org/cs/inject-autowire).
Jasně, že ano. Psal jsem to hlavně s ohledem na začátečníky, kteří se snadno do contructor hellu v presenteru zapletou a jeho vyřešení je pro ně obtížné, pokročilejší uživatelé tohle nepotřebují, ti si to rovnou předají přes kontruktor.

2017-01-10 13:53 UTC, janpecha commented on cs/docs/integrace-do-aplikace.md
> +    - LeanMapper\DefaultEntityFactory
Přidal jsem část o použití DI rozšíření (snad je použito správně).

2017-01-10 13:53 UTC, janpecha commented on cs/docs/integrace-do-aplikace.md
> +**Tip:** pokud nechcete, nebo nemůžete použít anotaci `@inject`, lze pro předání repositáře použít constructor nebo [`inject*()` metodu](http://pla.nette.org/cs/inject-autowire).
Přidal jsem předání přes konstruktor.

2017-01-12 13:41 UTC, castamir commented on cs/docs/integrace-do-aplikace.md
> +        host: localhost
přidej sem ještě driver, ať je to stejné jako dole

2017-01-12 13:47 UTC, janpecha commented on cs/docs/integrace-do-aplikace.md
> +        host: localhost
hotovo.

PS. přidal jsem ještě commit, který aktualizuje rok v patičce (z 2013-2016 na 2013-2017).

2017-01-12 16:19 UTC, castamir approved these changes

2017-01-12 16:19 UTC, merged

2017-01-12 16:19 UTC, castamir commented
great job ;)