Upravena stránka Entity
LeanMapper/LeanMapper.github.io pull request #11
Opened 2017-01-04 21:13 UTC by janpecha

Úprava a přeformátování stránky o entitách. Používá strukturu a texty z wiki (https://github.com/Tharos/LeanMapper/wiki/entity), zbytek textů je beze změn (maximálně přesun odstavců v rámci dokumentu). Chybí text o m:passThru a m:enum, výchozích hodnotách a vlastních příznacích.

Zkusil jsem nastřelit definici entity pomocí přístupových metod, ale nevím jestli úplně odpovídá ukázkové entitě.

2017-01-08 12:56 UTC, castamir requested changes
prosim o vyjadreni a pripadne doplneni tech drobnosti

2017-01-08 12:56 UTC, castamir commented on cs/docs/entity.md
> +Všimněte si, že ve všech předvedených metodách se přistupuje k protected proměnné `$row`. Entity v Lean Mapperu totiž vlastní data neudržují. Udržují jen instanci třídy `LeanMapper\Row`, která vlastn
vyhodit cast pro zajemce

2017-01-08 12:56 UTC, castamir commented on cs/docs/entity.md
> +## Vlastní příznaky {#toc-vlastni-priznaky}
prazdny nadpis? :)

2017-01-08 12:56 UTC, castamir commented on cs/docs/entity.md
> +## Defaultní (výchozí) hodnoty {#toc-vychozi-hodnoty}
prazdny nadpis? :)

2017-01-08 17:58 UTC, janpecha commented on cs/docs/entity.md
> +Všimněte si, že ve všech předvedených metodách se přistupuje k protected proměnné `$row`. Entity v Lean Mapperu totiž vlastní data neudržují. Udržují jen instanci třídy `LeanMapper\Row`, která vlastn
ok

2017-01-08 17:58 UTC, janpecha commented on cs/docs/entity.md
> +## Defaultní (výchozí) hodnoty {#toc-vychozi-hodnoty}
jj, v popisku zmiňuju, že tahle část zatím není dopsaná (stejně jako vlastní příznaky a "m:enum a m:passThru příznaky") - figuruje tu spíš jako osnova a aby se na ní dalo odkazovat z ostatních částí.

2017-01-10 13:33 UTC, janpecha commented on cs/docs/entity.md
> +Všimněte si, že ve všech předvedených metodách se přistupuje k protected proměnné `$row`. Entity v Lean Mapperu totiž vlastní data neudržují. Udržují jen instanci třídy `LeanMapper\Row`, která vlastn
upraveno.

2017-01-12 13:43 UTC, merged