Aktualizace
LeanMapper/LeanMapper.github.io pull request #9
Opened 2016-11-21 14:04 UTC by janpecha

* přepsána stránka Download
* přidána stránka "API dokumentace"
* mírně změněna struktura dokumentace 
* přidána stránka Rozšíření
* přidána stránka Články a videa
* opraven titulek u 5. kapitoly v Quick startu
* na úvodní stránky quick startu přidán přehled všech kapitol

2016-11-22 15:10 UTC, castamir requested changes

2016-11-22 15:10 UTC, castamir commented on cs/download.md
> +## Manuální instalace
manualni instalaci snad už doufám nikdo nedělá - dnes bych to označil za bad practise. Prosím odstranit....

2016-11-22 15:11 UTC, castamir commented
Ha, jsem vcera okomentoval a dnes vidim, ze github umi procesne resit i code review

2016-11-22 17:32 UTC, janpecha commented on cs/download.md
> +## Manuální instalace
Upraveno.

2016-11-23 09:25 UTC, janpecha commented
Stránku jsem upravil (nevím jestli přišla notifikace na můj komentář u commitu :) ).

2016-11-23 11:58 UTC, castamir commented
Došla, ale včera jsem se už nedostal ke komplu... po práci se na to mrknu

2016-11-24 00:32 UTC, castamir approved these changes

2016-11-24 00:32 UTC, merged